/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'wjyao' at '3/4/16 3:39 PM' with Gradle 2.6
 *
 * @author wjyao, @date 3/4/16 3:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
