import org.junit.Test;
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'wjyao' at '3/4/16 3:39 PM' with Gradle 2.6
 *
 * @author wjyao, @date 3/4/16 3:39 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
